DROP table citas_config
DROP  view RecepCitasWeb
DROP VIEW dbo.VistaAgenteDisponibilidad
DROP table AgentePersonal
DROP VIEW dbo.VistaMonitorTallerOperaciones
DROP TABLE dbo.CatColorTC
DROP TABLE dbo.CatOperacionesEstados
DROP TABLE dbo.CatOrdenesSituaciones
DROP TABLE dbo.UsuariosWeb
DROP PROCEDURE spCambiaSituacionWeb
DROP PROCEDURE xpSeguimientoweb
DROP TABLE dbo.CA_SeguimientoSesion
DROP TABLE [dbo].[conf_menuWeb]
DROP TABLE [dbo].[conf_permisoWeb]
DROP VIEW dbo.vwIndicadorTaller
DROP VIEW dbo.seguimientoTecnicosWeb
DROP VIEW dbo.vwIndicadorMovto
DROP VIEW dbo.vwIndicador_general
DROP VIEW dbo.vwIndicador_general2_filtros
DROP FUNCTION fnfechbit
DROP FUNCTION fnporcentajesbit
DROP FUNCTION usuarioSucursalbit
DROP VIEW vwOrdenesServicioMonitor
DROP VIEW vwOrdenesServicioMonitorD
DROP VIEW vwOrdenesServicioMonitorDtot
DROP VIEW vwOrdenesServicioMonitorDV2
DROP VIEW vwOrdenesServicioMonitorR
DROP VIEW vwOrdenesServicioMonitorTotal
