/*SOLAMENTE EN CASO DE NO EXISTIR LOS CAMPOS*/
EXEC spALTER_TABLE 'Art','CilindrosArt','INT NULL'
EXEC spALTER_TABLE 'Art','TransmisionArt','VARCHAR(20) NULL'
EXEC spALTER_TABLE 'VIN','Cilindros','INT NULL'